name: Trivy Image Scan Example

on: workflow_dispatch

permissions:
  security-events: write
  contents: read

jobs:
  trivy-scan-image:
    runs-on: ubuntu-latest
    steps:
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "image"
          image-ref: "python:3.4-alpine"
          ignore-unfixed: true
          vuln-type: "os,library"
          format: "sarif"
          output: "trivy-results.sarif"
          severity: "CRITICAL,HIGH"

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v4
        if: always() # Upload results even if vulnerabilities are found
        with:
          sarif_file: "trivy-results.sarif"
          category: "image-scan/python-alpine"
